package com.ideahub.model;
// Generated Feb 20, 2016 12:32:19 AM by Hibernate Tools 4.3.1

/**
 * IdeaCollaborator generated by hbm2java
 */
public class IdeaCollaborator implements java.io.Serializable {

    private IdeaCollaboratorId id;
    private Idea idea;
    private User user;
    private Byte inviteStatus;

    public IdeaCollaborator() {
    }

    public IdeaCollaborator(IdeaCollaboratorId id, Idea idea, User user) {
        this.id = id;
        this.idea = idea;
        this.user = user;
    }

    public IdeaCollaborator(IdeaCollaboratorId id, Idea idea, User user, Byte inviteStatus) {
        this.id = id;
        this.idea = idea;
        this.user = user;
        this.inviteStatus = inviteStatus;
    }

    public IdeaCollaboratorId getId() {
        return this.id;
    }

    public void setId(IdeaCollaboratorId id) {
        this.id = id;
    }

    public Idea getIdea() {
        return this.idea;
    }

    public void setIdea(Idea idea) {
        this.idea = idea;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Byte getInviteStatus() {
        return this.inviteStatus;
    }

    public void setInviteStatus(Byte inviteStatus) {
        this.inviteStatus = inviteStatus;
    }

}
