package com.ideahub.model;
// Generated Feb 20, 2016 12:32:19 AM by Hibernate Tools 4.3.1

/**
 * IdeaPartSuggestion generated by hbm2java
 */
public class IdeaPartSuggestion implements java.io.Serializable {

    private int id;
    private IdeaPart ideaPart;
    private User user;
    private String suggestion;
    private int upvotes;
    private int downvotes;

    public IdeaPartSuggestion() {
    }

    public IdeaPartSuggestion(int id, IdeaPart ideaPart, User user, String suggestion, int upvotes, int downvotes) {
        this.id = id;
        this.ideaPart = ideaPart;
        this.user = user;
        this.suggestion = suggestion;
        this.upvotes = upvotes;
        this.downvotes = downvotes;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public IdeaPart getIdeaPart() {
        return this.ideaPart;
    }

    public void setIdeaPart(IdeaPart ideaPart) {
        this.ideaPart = ideaPart;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getSuggestion() {
        return this.suggestion;
    }

    public void setSuggestion(String suggestion) {
        this.suggestion = suggestion;
    }

    public int getUpvotes() {
        return this.upvotes;
    }

    public void setUpvotes(int upvotes) {
        this.upvotes = upvotes;
    }

    public int getDownvotes() {
        return this.downvotes;
    }

    public void setDownvotes(int downvotes) {
        this.downvotes = downvotes;
    }

}
