package com.ideahub.model;
// Generated Feb 20, 2016 12:32:19 AM by Hibernate Tools 4.3.1

import lombok.*;
import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;

/**
 * IdeaCollaborator generated by hbm2java
 */


@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(of = { "id" })
@ToString
@Entity
@Table(name = "idea_collaborator")
@DynamicUpdate
public class IdeaCollaborator {
    @EmbeddedId
    private IdeaCollaboratorId id;

    @ManyToOne
    @JoinColumn(name = "idea_id")
    private Idea idea;

    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    @Column(name = "invite_status", nullable = false)
    private Byte inviteStatus;
}
