package com.ideahub.model;
// Generated Feb 20, 2016 12:24:43 AM by Hibernate Tools 4.3.1

/**
 * IdeaPartSuggestionId generated by hbm2java
 */
public class IdeaPartSuggestionId implements java.io.Serializable {

    private int id;
    private int userId;
    private int ideaPartId;

    public IdeaPartSuggestionId() {
    }

    public IdeaPartSuggestionId(int id, int userId, int ideaPartId) {
        this.id = id;
        this.userId = userId;
        this.ideaPartId = ideaPartId;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getIdeaPartId() {
        return this.ideaPartId;
    }

    public void setIdeaPartId(int ideaPartId) {
        this.ideaPartId = ideaPartId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof IdeaPartSuggestionId))
            return false;
        IdeaPartSuggestionId castOther = (IdeaPartSuggestionId) other;

        return (this.getId() == castOther.getId())
                && (this.getUserId() == castOther.getUserId())
                && (this.getIdeaPartId() == castOther.getIdeaPartId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getId();
        result = 37 * result + this.getUserId();
        result = 37 * result + this.getIdeaPartId();
        return result;
    }

}
