package com.ideahub.model;
// Generated Feb 20, 2016 12:32:19 AM by Hibernate Tools 4.3.1

import lombok.*;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.io.Serializable;

/**
 * IdeaCollaboratorId generated by hbm2java
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
@Embeddable
public class IdeaCollaboratorId implements Serializable {

    @Column(name = "user_id ", nullable = false)
    private int userId;

    @Column(name = "idea_id ", nullable = false)
    private int ideaId;
}
