package com.ideahub.model;
// Generated Feb 20, 2016 12:32:19 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * IdeaPart generated by hbm2java
 */
public class IdeaPart implements java.io.Serializable {

    private int id;
    private Idea idea;
    private IdeaPartType ideaPartType;
    private int userId;
    private int upvotes;
    private int downvotes;
    private String content;
    private String justification;
    private Set ideaPartSuggestions = new HashSet(0);

    public IdeaPart() {
    }

    public IdeaPart(int id, Idea idea, IdeaPartType ideaPartType, int userId, int upvotes, int downvotes, String content) {
        this.id = id;
        this.idea = idea;
        this.ideaPartType = ideaPartType;
        this.userId = userId;
        this.upvotes = upvotes;
        this.downvotes = downvotes;
        this.content = content;
    }

    public IdeaPart(int id, Idea idea, IdeaPartType ideaPartType, int userId, int upvotes, int downvotes, String content, String justification,
            Set ideaPartSuggestions) {
        this.id = id;
        this.idea = idea;
        this.ideaPartType = ideaPartType;
        this.userId = userId;
        this.upvotes = upvotes;
        this.downvotes = downvotes;
        this.content = content;
        this.justification = justification;
        this.ideaPartSuggestions = ideaPartSuggestions;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Idea getIdea() {
        return this.idea;
    }

    public void setIdea(Idea idea) {
        this.idea = idea;
    }

    public IdeaPartType getIdeaPartType() {
        return this.ideaPartType;
    }

    public void setIdeaPartType(IdeaPartType ideaPartType) {
        this.ideaPartType = ideaPartType;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getUpvotes() {
        return this.upvotes;
    }

    public void setUpvotes(int upvotes) {
        this.upvotes = upvotes;
    }

    public int getDownvotes() {
        return this.downvotes;
    }

    public void setDownvotes(int downvotes) {
        this.downvotes = downvotes;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getJustification() {
        return this.justification;
    }

    public void setJustification(String justification) {
        this.justification = justification;
    }

    public Set getIdeaPartSuggestions() {
        return this.ideaPartSuggestions;
    }

    public void setIdeaPartSuggestions(Set ideaPartSuggestions) {
        this.ideaPartSuggestions = ideaPartSuggestions;
    }

}
