package com.ideahub.model;
// Generated Feb 20, 2016 12:32:19 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Idea generated by hbm2java
 */
public class Idea implements java.io.Serializable {

    private int id;
    private User user;
    private Set ideaParts = new HashSet(0);
    private Set ideaCollaborators = new HashSet(0);

    public Idea() {
    }

    public Idea(int id, User user) {
        this.id = id;
        this.user = user;
    }

    public Idea(int id, User user, Set ideaParts, Set ideaCollaborators) {
        this.id = id;
        this.user = user;
        this.ideaParts = ideaParts;
        this.ideaCollaborators = ideaCollaborators;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Set getIdeaParts() {
        return this.ideaParts;
    }

    public void setIdeaParts(Set ideaParts) {
        this.ideaParts = ideaParts;
    }

    public Set getIdeaCollaborators() {
        return this.ideaCollaborators;
    }

    public void setIdeaCollaborators(Set ideaCollaborators) {
        this.ideaCollaborators = ideaCollaborators;
    }

}
