package com.ideahub.model;
// Generated Feb 20, 2016 12:32:19 AM by Hibernate Tools 4.3.1

import java.security.Principal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * User generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(of = { "id" })
@ToString(exclude = { "ideaCollaborators", "ideas", "ideaPartSuggestions" })
@Entity
@Table(name = "user")
@DynamicUpdate
public class User implements Principal {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @JsonIgnore
    private long id;

    @Column(name = "oauth_token")
    private String oauthToken;

    @Column(name = "username", unique = true, nullable = false)
    private String username;

    @Column(name = "email", unique = true, nullable = false)
    private String email;

    @Override
    public String getName() {
        return this.username;
    }

    // TODO: Uncomment this when we get collaborators in
    // @OneToMany(cascade = { CascadeType.ALL }, mappedBy = "user")
    // private Set<IdeaCollaborator> ideaCollaborators = new HashSet<>(0);
    // @OneToMany(cascade = { CascadeType.ALL })
    // @JoinColumn(name = "user_id") // Which column in the referenced table
    // will be joined
    // private Set<Idea> ideas;

    // @OneToMany(cascade = { CascadeType.ALL })
    // @JoinColumn(name = "user_id") // Which column in the referenced table
    // will be joined
    // private Set<IdeaPartSuggestion> ideaPartSuggestions;
}