package com.ideahub.model;
// Generated Feb 20, 2016 12:32:19 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private int id;
    private String oauthToken;
    private String username;
    private String email;
    private Set ideaCollaborators = new HashSet(0);
    private Set ideas = new HashSet(0);
    private Set ideaPartSuggestions = new HashSet(0);

    public User() {
    }

    public User(int id) {
        this.id = id;
    }

    public User(int id, String oauthToken, String username, String email, Set ideaCollaborators, Set ideas, Set ideaPartSuggestions) {
        this.id = id;
        this.oauthToken = oauthToken;
        this.username = username;
        this.email = email;
        this.ideaCollaborators = ideaCollaborators;
        this.ideas = ideas;
        this.ideaPartSuggestions = ideaPartSuggestions;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getOauthToken() {
        return this.oauthToken;
    }

    public void setOauthToken(String oauthToken) {
        this.oauthToken = oauthToken;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Set getIdeaCollaborators() {
        return this.ideaCollaborators;
    }

    public void setIdeaCollaborators(Set ideaCollaborators) {
        this.ideaCollaborators = ideaCollaborators;
    }

    public Set getIdeas() {
        return this.ideas;
    }

    public void setIdeas(Set ideas) {
        this.ideas = ideas;
    }

    public Set getIdeaPartSuggestions() {
        return this.ideaPartSuggestions;
    }

    public void setIdeaPartSuggestions(Set ideaPartSuggestions) {
        this.ideaPartSuggestions = ideaPartSuggestions;
    }

}
