-- MySQL Script generated by MySQL Workbench
-- 02/20/16 00:32:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ideahub
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ideahub` ;

-- -----------------------------------------------------
-- Schema ideahub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ideahub` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ideahub` ;

-- -----------------------------------------------------
-- Table `ideahub`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ideahub`.`user` ;

CREATE TABLE IF NOT EXISTS `ideahub`.`user` (
  `id` INT NOT NULL COMMENT '',
  `oauth_token` VARCHAR(45) NULL COMMENT '',
  `username` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ideahub`.`idea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ideahub`.`idea` ;

CREATE TABLE IF NOT EXISTS `ideahub`.`idea` (
  `id` INT NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_idea_user_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_idea_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `ideahub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ideahub`.`idea_collaborator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ideahub`.`idea_collaborator` ;

CREATE TABLE IF NOT EXISTS `ideahub`.`idea_collaborator` (
  `user_id` INT NOT NULL COMMENT '',
  `idea_id` INT NOT NULL COMMENT '',
  `invite_status` TINYINT(2) NULL COMMENT '',
  PRIMARY KEY (`user_id`, `idea_id`)  COMMENT '',
  INDEX `fk_user_has_idea_idea1_idx` (`idea_id` ASC)  COMMENT '',
  INDEX `fk_user_has_idea_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_has_idea_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ideahub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_idea_idea1`
    FOREIGN KEY (`idea_id`)
    REFERENCES `ideahub`.`idea` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ideahub`.`idea_part_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ideahub`.`idea_part_type` ;

CREATE TABLE IF NOT EXISTS `ideahub`.`idea_part_type` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `metadata` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ideahub`.`idea_part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ideahub`.`idea_part` ;

CREATE TABLE IF NOT EXISTS `ideahub`.`idea_part` (
  `id` INT NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `idea_id` INT NOT NULL COMMENT '',
  `idea_part_type_id` INT NOT NULL COMMENT '',
  `upvotes` INT NOT NULL COMMENT '',
  `downvotes` INT NOT NULL COMMENT '',
  `content` VARCHAR(100) NOT NULL COMMENT '',
  `justification` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_idea_part_idea_part_type1_idx` (`idea_part_type_id` ASC)  COMMENT '',
  INDEX `fk_idea_part_idea1_idx` (`idea_id` ASC)  COMMENT '',
  CONSTRAINT `fk_idea_part_idea_part_type1`
    FOREIGN KEY (`idea_part_type_id`)
    REFERENCES `ideahub`.`idea_part_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idea_part_idea1`
    FOREIGN KEY (`idea_id`)
    REFERENCES `ideahub`.`idea` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ideahub`.`idea_part_suggestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ideahub`.`idea_part_suggestion` ;

CREATE TABLE IF NOT EXISTS `ideahub`.`idea_part_suggestion` (
  `id` INT NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `idea_part_id` INT NOT NULL COMMENT '',
  `suggestion` VARCHAR(45) NOT NULL COMMENT '',
  `upvotes` INT NOT NULL DEFAULT 0 COMMENT '',
  `downvotes` INT NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_idea_part_suggestion_user1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_idea_part_suggestion_idea_part1_idx` (`idea_part_id` ASC)  COMMENT '',
  CONSTRAINT `fk_idea_part_suggestion_idea_part1`
    FOREIGN KEY (`idea_part_id`)
    REFERENCES `ideahub`.`idea_part` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idea_part_suggestion_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ideahub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
